list/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('list/',include('todolist.urls')),
]

todolist/urls.py
from django.urls import path
from todolist import views
app_name='todolist'
urlpatterns = [
    path('home/', views.home,name='主页'),
    path('edit/', views.edit,name='编辑'),
    path('about/', views.about, name='关于'),
    path('del/<forloop_counter>',views.delete,name='删除'),
]

todolist/models.py
from django.db import models

# Create your models here.

todolist/views.py
from django.shortcuts import render,redirect

# Create your views here.
lst=[
    {'待办事项':'吃饭','已完成':True},
    {'待办事项': '逛街', '已完成': False},

]
def home(request):
    global lst
    print(request.method)
    if request.method == "POST":
        content = request.POST.get('待办事项')
        print(content)
        if not content or content.strip() == '':
            return render(request, 'todolist/home.html', {'清单': lst,'警告':'请输入内容'})
        else:
            lst.append({'待办事项': content , '已完成': False})
            return render(request, 'todolist/home.html', {'清单': lst})
    else:
        return render(request, 'todolist/home.html', {'清单': lst})

def edit(request):
    return render(request, 'todolist/edit.html')

def about(request):
    return render(request, 'todolist/about.html')
def delete(request,forloop_counter):
    global lst
    forloop_counter=int(forloop_counter)-1
    lst.pop(forloop_counter)
    return redirect('todolist:主页')

todolist/templates/todolist/about.html
{% extends 'todolist/base.html' %}
{% block 标题 %}
    关于
{% endblock %}
{% block 关于高亮 %}
    active
{% endblock %}
{% block 主体 %}
    <main role="main" class="container">
      <br>
      <h4>一款小巧、简洁的待办清单工具，帮你规划日常事务。</h4>
    </main>

{% endblock %}

todolist/templates/todolist/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>
      {% block 标题 %}
            未命名
      {% endblock %}
    
    
    
    </title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.bootcss.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <style>
        #topnav{
            font-size: 1.35em;
            padding-left: 5em;
            padding-right: 5em;
            height: 2.5em;
        }
        nav input{
          width: 39%!important;
        }
        .no-underline>tr>td>a:hover{
          text-decoration: none;
        }
        #line-through{
          text-decoration: line-through;
        }
    </style>
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4" id="topnav">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item {% block 待办高亮 %}{% endblock %}">
            <a class="nav-link" href='{% url 'todolist:主页' %}'>待办清单</a>
          </li>
          <li class="nav-item {% block 关于高亮 %}{% endblock %}">
            <a class="nav-link" href='{% url 'todolist:关于' %}'>关于本站</a>
          </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0 col-7 justify-content-end" action="" method="post">
            {% csrf_token %}
          <input name="待办事项" class="form-control mr-sm-2" type="text" placeholder="待办事项" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">添加</button>
        </form>
      </div>
    </nav>
{% block 主体 %}

{% endblock %}

<!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://cdn.bootcss.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

todolist/templates/todolist/edit.html
{% extends 'todolist/base.html' %}
{% block 标题 %}
    编辑清单
{% endblock %}
{% block 主体 %}
 <main role="main" class="container">
      <br>
      <form id="form-edit">
        <div class="form-group">
          <label for="editTodo"></label>
          <input class="form-control form-control-lg" id="editTodo" type="text" value="遛狗">
          <small id="help" class="form-text text-muted">在这里编辑待办事项</small>
        </div>
        <button type="button" class="btn btn-primary btn-lg btn-block">提交</button>
      </form>
    </main>
{% endblock %}

todolist/templates/todolist/home.html
{% extends 'todolist/base.html' %}
{% block 标题 %}
    待办清单
{% endblock %}
{% block 待办高亮 %}
         active
{% endblock %}
{% block 主体 %}
    {{ 警告 }}
  <main role="main" class="container">
      <br>
      <div class="table-responsive">
        <table class="table table-hover">
          <thead class="thead-light">
            <tr>
              <th>序号</th>
              <th>待办事项</th>
              <th>编辑</th>
              <th>划掉</th>
              <th>删除</th>
            </tr>
          </thead>
          <tbody class="no-underline">
          {% for things in 清单 %}
              {% if things.已完成 %}
               <tr class="table-dark">
                   <th class="text-dark" scope="row">{{ forloop.counter }}</th>
                   <td class="text-dark" id="line-through">{{ things.待办事项 }}</td>
                   <td class="text-secondary">不可编辑</td>
                   <td><a class="text-info" href="#">撤销</a></td>
                   <td><a class="text-danger" href="#">删除</a></td>
                </tr>
              {% else %}
            <tr>
              <th scope="row">{{ forloop.counter }}</th>
              <td>{{ things.待办事项 }}</td>
              <td><a class="text-success" href="{% url 'todolist:编辑' %}">编辑</a></td>
              <td><a href="#">划掉</a></td>
              <td><a class="text-info" href="{% url 'todolist:删除'  forloop.counter%}">删除</a></td>
            </tr>
              {% endif %}
          {% endfor %}
            <tr>

{#              <th scope="row">2</th>#}

{#              <td>看一会小说</td>#}

{#              <td><a class="text-success" href="#">编辑</a></td>#}

{#              <td><a href="#">划掉</a></td>#}

{#              <td><a class="text-info" href="#">删除</a></td>#}

{#            </tr>#}

{#            <tr>#}

{#              <th scope="row">3</th>#}

{#              <td>散散步</td>#}

{#              <td><a class="text-success" href="#">编辑</a></td>#}

{#              <td><a href="#">划掉</a></td>#}

{#              <td><a class="text-info" href="#">删除</a></td>#}

{#            </tr>#}

          </tbody>

        </table>

      </div>

    </main>
{% endblock %}